const formatCommandsValue = {
    pct   : v => `${v.toFixed(1)} %`,
    rpm   : v => `${v.toFixed(0)} tr/min`,
    kmh   : v => `${v.toFixed(0)} km/h`,
    tempC : v => `${v.toFixed(0)} °C`,
    g_s   : v => `${v.toFixed(2)} g/s`,
    volt  : v => `${v.toFixed(2)} V`,
    sec   : v => `${v.toFixed(0)} s`,
    dist  : v => `${v.toFixed(0)} km`,
    kPa   : v => `${v.toFixed(2)} kPa`,
    BTDC  : v => `${v.toFixed(1)} ° BTDC`,
    mA    : v => `${v.toFixed(2)} mA`,

    raw   : v => v,
    str   : v => `${v}`,
    byteA : v => v,
};

export const OBD_COMMANDS = {
    RPM:                            { name: 'Régime moteur',            formatValue: formatCommandsValue.rpm  },
    SPEED:                          { name: 'Vitesse véhicule',         formatValue: formatCommandsValue.kmh  },
    COOLANT_TEMP:                   { name: 'Temp. liquide',            formatValue: formatCommandsValue.tempC },
    INTAKE_TEMP:                    { name: 'Temp. admission',          formatValue: formatCommandsValue.tempC },
    INTAKE_PRESSURE:                { name: 'Pression admission',       formatValue: formatCommandsValue.kPa },
    BAROMETRIC_PRESSURE:            { name: 'Pression barométrique',    formatValue: formatCommandsValue.kPa },
    TIMING_ADVANCE:                 { name: 'Avance allumage',          formatValue: formatCommandsValue.BTDC },
    THROTTLE_POS:                   { name: 'Ouverture papillon',       formatValue: formatCommandsValue.pct },
    THROTTLE_ACTUATOR:              { name: 'Actionneur papillon',      formatValue: formatCommandsValue.pct },
    THROTTLE_POS_B:                 { name: 'Papillon (capteur B)',     formatValue: formatCommandsValue.pct },
    RELATIVE_THROTTLE_POS:          { name: 'Papillon (relatif)',       formatValue: formatCommandsValue.pct },
    ENGINE_LOAD:                    { name: 'Charge moteur',            formatValue: formatCommandsValue.pct },
    ABSOLUTE_LOAD:                  { name: 'Charge absolue',           formatValue: formatCommandsValue.pct },
    LONG_FUEL_TRIM_1:               { name: 'LTFT Banc 1',              formatValue: formatCommandsValue.pct },
    SHORT_FUEL_TRIM_1:              { name: 'STFT Banc 1',              formatValue: formatCommandsValue.pct },
    MAF:                            { name: 'Débit massique air',       formatValue: formatCommandsValue.g_s },
    EVAPORATIVE_PURGE:              { name: 'Purge EVAP',               formatValue: formatCommandsValue.pct },
    COMMANDED_EGR:                  { name: 'EGR commandée',            formatValue: formatCommandsValue.pct },
    CATALYST_TEMP_B1S1:             { name: 'T° catalyseur B1S1',       formatValue: formatCommandsValue.tempC },
    CATALYST_TEMP_B1S2:             { name: 'T° catalyseur B1S2',       formatValue: formatCommandsValue.tempC },
    O2_S1_WR_VOLTAGE:               { name: 'Lambda amont (V)',         formatValue: formatCommandsValue.volt },
    O2_S1_WR_CURRENT:               { name: 'Lambda amont (mA)',        formatValue: formatCommandsValue.mA },
    O2_B1S2:                        { name: 'Lambda aval (V)',          formatValue: formatCommandsValue.volt },
    ELM_VOLTAGE:                    { name: 'Tension interface',        formatValue: formatCommandsValue.volt },
    CONTROL_MODULE_VOLTAGE:         { name: 'Tension calculateur',      formatValue: formatCommandsValue.volt },
    RUN_TIME:                       { name: 'Temps moteur allumé',      formatValue: formatCommandsValue.sec },
    RUN_TIME_MIL:                   { name: 'Run-time depuis MIL',      formatValue: formatCommandsValue.sec },
    DISTANCE_W_MIL:                 { name: 'Distance avec MIL',        formatValue: formatCommandsValue.dist },
    TIME_SINCE_DTC_CLEARED:         { name: 'Temps depuis RAZ DTC',     formatValue: formatCommandsValue.sec },
    DISTANCE_SINCE_DTC_CLEAR:       { name: 'Distance depuis RAZ DTC',  formatValue: formatCommandsValue.dist },
    /*
    FUEL_TYPE:                      { name: 'Type carburant',           formatValue: formatCommandsValue.str },
    OBD_COMPLIANCE:                 { name: 'Norme OBD',                formatValue: formatCommandsValue.str },
    COMMANDED_EQUIV_RATIO:          { name: 'Lambda cible',             formatValue: formatCommandsValue.raw },
    WARMUPS_SINCE_DTC_CLEAR:        { name: 'Cycles chauffe depuis RAZ',formatValue: formatCommandsValue.raw },
    GET_DTC:                        { name: 'Codes DTC (actifs)',       formatValue: formatCommandsValue.str },
    GET_CURRENT_DTC:                { name: 'Codes DTC (courants)',     formatValue: formatCommandsValue.str },
    VIN:                            { name: 'VIN',                      formatValue: formatCommandsValue.byteA },
    ELM_VERSION:                    { name: 'Version ELM',              formatValue: formatCommandsValue.str },
    CVN:                            { name: 'CVN',                      formatValue: formatCommandsValue.str },
    CALIBRATION_ID:                 { name: 'Calibration ID',           formatValue: formatCommandsValue.byteA },
    PIDS_B:                         { name: 'Bitmap PIDs 40-5F',        formatValue: formatCommandsValue.str },
    MIDS_A:                         { name: 'Bitmap MIDs A',            formatValue: formatCommandsValue.str },
    PIDS_9A:                        { name: 'Bitmap PIDs 9A',           formatValue: formatCommandsValue.str },
    O2_SENSORS:                     { name: 'Capteurs O₂ présents',     formatValue: formatCommandsValue.str },
    PIDS_A:                         { name: 'Bitmap PIDs 20-3F',        formatValue: formatCommandsValue.str },
    PIDS_C:                         { name: 'Bitmap PIDs 60-7F',        formatValue: formatCommandsValue.str },
    FUEL_STATUS:                    { name: 'Boucle carburant',         formatValue: formatCommandsValue.str },
    DTC_STATUS:                     { name: 'Statut DTC',               formatValue: formatCommandsValue.str },
    STATUS:                         { name: 'Statut ECU',               formatValue: formatCommandsValue.str },
    */
};